dyn_o_mite:
  listen: 0.0.0.0:6379
  dyn_listen: 0.0.0.0:6378
  stats_listen: 0.0.0.0:2222
  dyn_seed_provider: simple_provider
  tokens: ${DYNO_SEED}
  servers:
  - ${REDIS_HOST}:6379:1
  data_store: 0
